name: all-the-things
on: push
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Set environment variables
        run: |
          GIT_SHORT_SHA=${GITHUB_SHA:0:8}
          echo "git_short_sha=${GIT_SHORT_SHA}" >> ${GITHUB_ENV}

      - name: Enable experimental Docker features
        run: |
          sudo mv /etc/docker/daemon.json{,.bak}
          sudo cat /etc/docker/daemon.json.bak | jq '. + {experimental: true}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart
      - uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Setup Nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-20.09
          extra_nix_config: |
            max-jobs = auto
      - name: Setup Cachix
        uses: cachix/cachix-action@v8
        with:
          name: matobet-rpi
          authToken: ${{ secrets.CACHIX_TOKEN }}
          extraPullNames: iohk
      - run: nix-build docker.nix 
      - name: Import image as ARM
        run: |
          docker load < result
          docker inspect dyco-mirror-bot:latest

      - name: Push image to Quay
        env:
          IMAGE_NAME: quay.io/dyco/dyco-mirror
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: |
          docker tag dyco-mirror-bot:latest "${IMAGE_NAME}:latest" 
          docker tag dyco-mirror-bot:latest "${IMAGE_NAME}:${git_short_sha}" 
          docker push "${IMAGE_NAME}:latest"
          docker push "${IMAGE_NAME}:${git_short_sha}"

